### ISSUE TITLE
trackOffset and startOffset are xs:double

### ISSUE THREAD

**Issue by LupusUmbrae** [senbox-org/s3tbx#10]
Trying again with reading a manifest file i hit another issues in the [reader](https://github.com/senbox-org/s3tbx/blob/master/s3tbx-sentinel3-reader/src/main/java/org/esa/s3tbx/dataio/s3/slstr/SlstrLevel1ProductFactory.java#L114), you are parsing trackOffset and startOffset as Integers but the Sentinal 3 XSD defines the element type as xs:double

**Comment by marpet** [comment]
Thanks for the hint. But how can we know that it is of type double? Is the XSD somewhere accessible? Or is there an other documentation which describes it?

**Comment by LupusUmbrae** [comment]
I have a copy of the Schema and the documentation for it, but i cannot for the life of me find a link on ESA's websites. However I think the schema is over a year old so it's possible you already have a copy from the early SLSTR work.

In the following [document](https://sentinel.esa.int/documents/247904/1872792/Sentinel-3_Product_Data_Format_Specification-SLSTR_Level-1-2_Products), AD-5 is the reference to the schemas, however looking for the id `S3IPF.PDS.009` just brings up this PDF

**Comment by marpet** [comment]
I also talked to my colleague but we haven received the schema till now.

Thanks for information
