### ISSUE TITLE
Sentinel 3 olci L2 tar files cannot be loaded correctly

### ISSUE THREAD

**Issue by henggu1011** [senbox-org/s3tbx#12]
When I open S3A_OL_2_WFR tar files on SNAP, only the first NetCDF data file is loaded, other files are not loaded. Is it a bug or is it designed that way?

**Comment by marpet** [comment]
You need to unpack the data first other wise a generic reader is used which can not properly read the Sentinel-3 data.

**Comment by henggu1011** [comment]
thanks! It works with the unpacked files.
Heng
