### ISSUE TITLE
SNAP does not read full SLSTR product

### ISSUE THREAD

**Issue by DaveSmith-RAL** [senbox-org/s3tbx#13]
SNAP ingests SLSTR L1 products from the manifest file ok.  However, the product navigator does not reflect the product structure very well and there are several missing datasets (including several quality datasets) and does not show the orphan pixels.  This means that SNAP is not suitable for evaluating the details of L1 products.

**Comment by marpet** [comment]
Thanks for your report.
Can you name some of the missing datasets exemplarily?
As they don't belong to the grid they are not shown.
How would you like to see the orphan pixels? How would you like to work with them?
There is a regridding tool in development which will make use of the orphan pixels.
