### ISSUE TITLE
WRITING problem from GRAPH BUILDER to BATCH PROCESSING

### ISSUE THREAD

**Issue by LUCADEMARCHI** [senbox-org/s3tbx#18]
Hi there,
I am new to the community. I have an issue when loading a Graph Builder file into Batch-processing. 
My graph building file contains the "Write"options. When I save and load it into the batch-processing, the "Write"options disappear:
![2018-04-03_15-18-05](https://user-images.githubusercontent.com/38039630/38251611-40d5ec3e-3752-11e8-8399-f3aef37e0cd7.png)
The result is that I get the correct number of result files, but each of them contains exactly the same layer image, it seems like it is overwriting them, but with different file names. 
Any solution to this issue?
thanks
LucaD

**Comment by marpet** [comment]
Hi Luca,

thanks for the report. In general, such issues are better posted in the [SNAP forum](http://forum.step.esa.int). There it get's more attention

**Comment by LUCADEMARCHI** [comment]
ok, I will post it there,
thanks!

**Comment by marpet** [comment]
http://forum.step.esa.int/t/writing-problem-from-graph-builder-to-batch-processing/9548?u=marpet
