### ISSUE TITLE
MetOp AVHRR Product reader

### ISSUE THREAD

**Issue by gritk** [senbox-org/s3tbx#6]
Even though the MetOp Avhrr reader is still missing for SNAP the current version for BEAM has some problem when calculating the reflectance values. This should be considered when migrating the MetOp Avhrr reader to SNAP.

Calculation of reflectance from the radiance doesn't work properly in case of the MetOp L1b products, because they include the inband_radiance instead of the spectral radiance and therefore the equivalent_filter_width should not be taken into account .

Depending on which type of radiance band is included in the product, the reflecance in percent is calculated as follows:

reflectance = 100 * (inband_radiance * PI)/ (filtered_extraterrestrial_solar_irradiance)

or

reflectance = 100 *  (spectral_radiance * equivalent_filter_width * PI)/ (filtered_extraterrestrial_solar_irradiance)

with 

 inband_radiance = spectral_radiance * equivalent_filter_width

**Comment by marpet** [comment]
This has been done only for BEAM right now.
The migration of the METOP AVHRR module into s3tbx is still outstanding.

**Comment by marpet** [comment]
It is now migrated to the current master man will be released with SNAP 4
